[pytest]
addopts = --html=report.html
# addopts = --html=report.html --self-contained-html
# addopts = --headed

markers =
    mobile: these tests work only when mobile env is configured
    desktop-only: tests that only run in full frowser window